# Generated by Django 5.2 on 2025-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
                ('mca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='academics.materiacomisionanio')),
            ],
        ),
        migrations.CreateModel(
            name='ResenaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('MATERIA', 'Materia'), ('COMISION', 'Comisión'), ('TITULAR', 'Profesor Titular'), ('JTP', 'Jefe de Trabajos Prácticos')], max_length=16)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas_items', to='academics.comision')),
                ('jtp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas_como_jtp', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas_items', to='academics.materia')),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.resena')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas_como_titular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['mca'], name='academics_r_mca_id_507e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['alumno', 'mca'], name='academics_r_alumno__9999ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('alumno', 'mca'), name='uq_resena_alumno_mca'),
        ),
        migrations.AddIndex(
            model_name='resenaitem',
            index=models.Index(fields=['target_type'], name='academics_r_target__163add_idx'),
        ),
        migrations.AddConstraint(
            model_name='resenaitem',
            constraint=models.UniqueConstraint(fields=('resena', 'target_type'), name='uq_item_por_tipo_por_resena'),
        ),
        migrations.AddConstraint(
            model_name='resenaitem',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), name='chk_item_puntuacion_1_5'),
        ),
        migrations.AddConstraint(
            model_name='resenaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'MATERIA'), ('materia__isnull', False), ('comision__isnull', True), ('titular__isnull', True), ('jtp__isnull', True)), models.Q(('target_type', 'MATERIA'), _negated=True), _connector='OR'), name='chk_item_materia_fk'),
        ),
        migrations.AddConstraint(
            model_name='resenaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'COMISION'), ('comision__isnull', False), ('materia__isnull', True), ('titular__isnull', True), ('jtp__isnull', True)), models.Q(('target_type', 'COMISION'), _negated=True), _connector='OR'), name='chk_item_comision_fk'),
        ),
        migrations.AddConstraint(
            model_name='resenaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'TITULAR'), ('titular__isnull', False), ('materia__isnull', True), ('comision__isnull', True), ('jtp__isnull', True)), models.Q(('target_type', 'TITULAR'), _negated=True), _connector='OR'), name='chk_item_titular_fk'),
        ),
        migrations.AddConstraint(
            model_name='resenaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'JTP'), ('jtp__isnull', False), ('materia__isnull', True), ('comision__isnull', True), ('titular__isnull', True)), models.Q(('target_type', 'JTP'), _negated=True), _connector='OR'), name='chk_item_jtp_fk'),
        ),
    ]
