# Generated by Django 5.2 on 2025-09-29 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_resena_resenaitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('PROMOCIONADA', 'Promocionada'), ('APROBADA', 'Aprobada')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('mca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academics.materiacomisionanio')),
            ],
            options={
                'indexes': [models.Index(fields=['alumno'], name='academics_n_alumno__c7c658_idx'), models.Index(fields=['mca'], name='academics_n_mca_id_6a7358_idx'), models.Index(fields=['estado'], name='academics_n_estado_f58683_idx')],
                'unique_together': {('alumno', 'mca')},
            },
        ),
    ]
