# Generated by Django 5.2 on 2025-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_materia_created_at_materia_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icono',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='icono',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
