# Generated by Django 5.2 on 2025-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_department_icono_alter_materia_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='icono',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='comision',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='materias/'),
        ),
    ]
