# Generated by Django 5.2 on 2025-09-30 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_nota'),
        ('academics', '0005_comision_icono_comision_imagen'),
    ]

    operations = [
    ]
