# Generated by Django 5.2 on 2025-10-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_merge_0003_nota_0005_comision_icono_comision_imagen'),
    ]

    operations = [
    ]
