# Generated by Django 5.2 on 2025-11-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_skip_department_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoredWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
