# Generated by Django 5.2 on 2025-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_censoredword'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materiacomisionanio',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
