# Generated by Django 5.2 on 2025-09-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
