# Generated by Django 5.2 on 2025-10-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_user_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
