# Generated by Django 5.2 on 2025-10-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ALU', 'Alumno'), ('PRO', 'Profesor'), ('ADM', 'Administrador')], max_length=3),
        ),
    ]
